# Generated by Django 4.0.6 on 2022-07-29 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='state',
            field=models.CharField(default='unresolved', max_length=10),
        ),
    ]
