# Generated by Django 4.0.6 on 2022-08-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_ticket_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='state',
            field=models.CharField(choices=[('unresolved', 'Unresolved'), ('resolved', 'Resolved'), ('frozen', 'Frozen')], default='unresolved', max_length=10),
        ),
    ]
