# Generated by Django 4.0.6 on 2022-08-06 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_ticket_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='is_deleted',
        ),
    ]
